// Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');
const genMarkdown = require('./utils/generateMarkdown.js');


// Create an array of questions for user input
const questions = ['What is your GitHub username? ', 'What is your email address? ', 
'What is your project s name? ', 'Please write a short description of your project ', 
'What commmand should be run to install dependencies? ', 'What command should be run to run tests? ',
'What does the user need to know about using your project? ', 'How does user contribute to developing your project? ',
'What kind of license should your project have? '  ];

// Create a function to write sample README file
function writeToFile(fileName) {
  inquirer
    .prompt([
        {
            type: 'input',
            name: 'gitHub',
            message: questions[0],
        },
        {
            type: 'input',
            name: 'email',
            message: questions[1],
        },
        {
            type: 'input',
            name: 'projTitle',
            message: questions[2],
        },
        {
            type: 'input',
            name: 'description',
            message: questions[3],
        },
        {
            type: 'input',
            name: 'install',
            message: questions[4],
        },
        {
            type: 'input',
            name: 'test',
            message: questions[5],
        },
        {
            type: 'input',
            name: 'usage',
            message: questions[6],
        },
        {
            type: 'input',
            name: 'contribute',
            message: questions[7],
        },
        {
            type: 'list',
            name: 'license',
            message: questions[8],
            choices: [
                "MIT",
                "APACHE2.0", 
                "GPL3.0", 
                "BSD3.0", new inquirer.Separator(),
                "No License"
            ]
        },
    ])
    .then((answer) => {
        console.log(answer);
        const readmeContent = genMarkdown(answer);
        // pass the answer and write the content generated by generateMarkdown() to a README file
        fs.writeFile(fileName, readmeContent, (error) => {    
            error ? console.error(error) : console.log('Success! sampleREADME.md is generated, Please Check')
            }
          );
    });
}

// Create a function to initialize app
function init() {
    writeToFile('sampleREADME.md');

}

// Function call to initialize app
init();
